name: Deploy via SSH

on:
  push:
    branches:
      - main  # or 'master' or any branch you want to auto-deploy on

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/your-app-folder   # <-- change this to your app path
            git pull origin main              # optional, if code lives on EC2
            docker compose pull               # pull new images
            docker compose down               # stop old containers
            docker compose up -d --build      # build and run in background
