name: Deploy to EC2 using SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 54.82.4.40
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd ~/ci-cd-nodejs
          git config --global --add safe.directory /home/ubuntu/ci-cd-nodejs
          git pull origin main
          docker compose down
          docker compose up -d --build
