name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ~/ci-cd-nodejs
          git config --global --add safe.directory /home/ubuntu/ci-cd-nodejs
          echo "Pulling latest code..."
          git pull origin main
          
          echo "Stopping old containers..."
          docker compose down

          echo "Building fresh containers..."
          docker compose build --no-cache

          echo "Starting containers..."
          docker compose up -d

          echo "Deployment complete ✅"
